-- Thêm dữ liệu vào bảng departments (danh sách các khoa trong bệnh viện)
INSERT INTO departments (name) VALUES
-- Dị ứng - Allergy
('Allergy'),
-- Chấn thương chỉnh hình - Orthopedics
('Orthopedics'),
-- Nha khoa - Dentistry
('Dentistry'),
-- Thần kinh - Neurology
('Neurology'),
-- Tiêu hóa - Gastroenterology
('Gastroenterology'),
-- Tiết niệu - Urology
('Urology'),
-- Gan mật - Hepatology
('Hepatology'),
-- Da liễu - Dermatology
('Dermatology'),
-- Tâm thần - Psychiatry
('Psychiatry'),
-- Tai Mũi Họng - Otorhinolaryngology (ENT)
('Otorhinolaryngology (ENT)'),
-- Nội tổng quát - General Medicine
('General Medicine'),
-- Sản phụ khoa - Obstetrics and Gynecology
('Obstetrics and Gynecology'),
-- Hô hấp - Pulmonology
('Pulmonology'),
-- Nội tiết - Endocrinology
('Endocrinology'),
-- Huyết học - Hematology
('Hematology'),
-- Thận - Nephrology
('Nephrology'),
-- Tim mạch - Cardiology
('Cardiology'),
-- Cơ xương khớp - Rheumatology
('Rheumatology'),
-- Mắt - Ophthalmology
('Ophthalmology');

-- Thêm các triệu chứng vào bảng Symptoms
INSERT INTO Symptoms (name_en, name_vi) VALUES
                                            ('anxiety and nervousness', 'Lo âu và căng thẳng'),
                                            ('depression', 'Trầm cảm'),
                                            ('shortness of breath', 'Khó thở'),
                                            ('depressive or psychotic symptoms', 'Triệu chứng trầm cảm hoặc tâm thần'),
                                            ('sharp chest pain', 'Đau ngực sắc'),
                                            ('dizziness', 'Chóng mặt'),
                                            ('insomnia', 'Mất ngủ'),
                                            ('abnormal involuntary movements', 'Chuyển động bất thường không tự nguyện'),
                                            ('chest tightness', 'Căng ngực'),
                                            ('palpitations', 'Tim đập nhanh'),
                                            ('irregular heartbeat', 'Nhịp tim không đều'),
                                            ('breathing fast', 'Thở nhanh'),
                                            ('hoarse voice', 'Khàn giọng'),
                                            ('sore throat', 'Đau họng'),
                                            ('difficulty speaking', 'Khó nói'),
                                            ('cough', 'Ho'),
                                            ('nasal congestion', 'Tắc nghẽn mũi'),
                                            ('throat swelling', 'Sưng họng'),
                                            ('diminished hearing', 'Giảm thính lực'),
                                            ('lump in throat', 'Cục u trong họng'),
                                            ('throat feels tight', 'Cảm giác thắt nghẹt họng'),
                                            ('difficulty in swallowing', 'Khó nuốt'),
                                            ('skin swelling', 'Sưng da'),
                                            ('retention of urine', 'Giữ nước tiểu'),
                                            ('groin mass', 'Khối u vùng bẹn'),
                                            ('leg pain', 'Đau chân'),
                                            ('hip pain', 'Đau hông'),
                                            ('suprapubic pain', 'Đau vùng trên xương mu'),
                                            ('blood in stool', 'Máu trong phân'),
                                            ('lack of growth', 'Thiếu sự phát triển'),
                                            ('emotional symptoms', 'Triệu chứng cảm xúc'),
                                            ('elbow weakness', 'Yếu khớp khuỷu tay'),
                                            ('back weakness', 'Yếu lưng'),
                                            ('pus in sputum', 'Mủ trong đờm'),
                                            ('symptoms of the scrotum and testes', 'Triệu chứng của bìu và tinh hoàn'),
                                            ('swelling of scrotum', 'Sưng bìu'),
                                            ('pain in testicles', 'Đau tinh hoàn'),
                                            ('flatulence', 'Chướng bụng'),
                                            ('pus draining from ear', 'Mủ chảy từ tai'),
                                            ('jaundice', 'Vàng da'),
                                            ('mass in scrotum', 'Khối u trong bìu'),
                                            ('white discharge from eye', 'Dịch trắng từ mắt'),
                                            ('irritable infant', 'Trẻ quấy khóc'),
                                            ('abusing alcohol', 'Lạm dụng rượu'),
                                            ('fainting', 'Ngất xỉu'),
                                            ('hostile behavior', 'Hành vi thù địch'),
                                            ('drug abuse', 'Lạm dụng thuốc'),
                                            ('sharp abdominal pain', 'Đau bụng sắc'),
                                            ('feeling ill', 'Cảm thấy ốm'),
                                            ('vomiting', 'Nôn mửa'),
                                            ('headache', 'Đau đầu'),
                                            ('nausea', 'Buồn nôn'),
                                            ('diarrhea', 'Tiêu chảy'),
                                            ('vaginal itching', 'Ngứa âm đạo'),
                                            ('vaginal dryness', 'Khô âm đạo'),
                                            ('painful urination', 'Đau khi đi tiểu'),
                                            ('involuntary urination', 'Tiểu không tự nguyện'),
                                            ('pain during intercourse', 'Đau khi quan hệ tình dục'),
                                            ('frequent urination', 'Đi tiểu thường xuyên'),
                                            ('lower abdominal pain', 'Đau bụng dưới'),
                                            ('vaginal discharge', 'Dịch âm đạo'),
                                            ('blood in urine', 'Máu trong nước tiểu'),
                                            ('hot flashes', 'Cơn nóng bừng'),
                                            ('intermenstrual bleeding', 'Chảy máu giữa kỳ kinh'),
                                            ('hand or finger pain', 'Đau tay hoặc ngón tay'),
                                            ('wrist pain', 'Đau cổ tay'),
                                            ('hand or finger swelling', 'Sưng tay hoặc ngón tay'),
                                            ('arm pain', 'Đau tay'),
                                            ('wrist swelling', 'Sưng cổ tay'),
                                            ('arm stiffness or tightness', 'Cứng hoặc thắt chặt tay'),
                                            ('arm swelling', 'Sưng tay'),
                                            ('hand or finger stiffness or tightness', 'Cứng hoặc thắt chặt tay hoặc ngón tay'),
                                            ('wrist stiffness or tightness', 'Cứng hoặc thắt chặt cổ tay'),
                                            ('lip swelling', 'Sưng môi'),
                                            ('toothache', 'Đau răng'),
                                            ('abnormal appearing skin', 'Da xuất hiện bất thường'),
                                            ('skin lesion', 'Tổn thương da'),
                                            ('acne or pimples', 'Mụn hoặc mụn nhọt');
-- Thêm các triệu chứng vào bảng Symptoms
INSERT INTO Symptoms (name_en, name_vi) VALUES
                                            ('dry lips', 'Môi khô'),
                                            ('facial pain', 'Đau mặt'),
                                            ('mouth ulcer', 'Loét miệng'),
                                            ('skin growth', 'Tăng trưởng da'),
                                            ('eye deviation', 'Lệch mắt'),
                                            ('diminished vision', 'Giảm thị lực'),
                                            ('double vision', 'Mắt đôi'),
                                            ('cross-eyed', 'Lác mắt'),
                                            ('symptoms of eye', 'Triệu chứng mắt'),
                                            ('pain in eye', 'Đau mắt'),
                                            ('eye moves abnormally', 'Mắt di chuyển bất thường'),
                                            ('abnormal movement of eyelid', 'Chuyển động bất thường của mí mắt'),
                                            ('foreign body sensation in eye', 'Cảm giác dị vật trong mắt'),
                                            ('irregular appearing scalp', 'Da đầu xuất hiện bất thường'),
                                            ('swollen lymph nodes', 'Sưng hạch bạch huyết'),
                                            ('back pain', 'Đau lưng'),
                                            ('neck pain', 'Đau cổ'),
                                            ('low back pain', 'Đau lưng dưới'),
                                            ('pain of the anus', 'Đau hậu môn'),
                                            ('pain during pregnancy', 'Đau trong thai kỳ'),
                                            ('pelvic pain', 'Đau vùng chậu'),
                                            ('impotence', 'Bất lực'),
                                            ('infant spitting up', 'Trẻ nôn ra'),
                                            ('vomiting blood', 'Nôn ra máu'),
                                            ('regurgitation', 'Trào ngược'),
                                            ('burning abdominal pain', 'Đau bụng nóng rát'),
                                            ('restlessness', 'Bồn chồn'),
                                            ('symptoms of infants', 'Triệu chứng của trẻ sơ sinh'),
                                            ('wheezing', 'Thở khò khè'),
                                            ('peripheral edema', 'Phù ngoại biên'),
                                            ('neck mass', 'Khối u cổ'),
                                            ('ear pain', 'Đau tai'),
                                            ('jaw swelling', 'Sưng hàm'),
                                            ('mouth dryness', 'Khô miệng'),
                                            ('neck swelling', 'Sưng cổ'),
                                            ('knee pain', 'Đau đầu gối'),
                                            ('foot or toe pain', 'Đau chân hoặc ngón chân'),
                                            ('bowlegged or knock-kneed', 'Chân vòng kiềng hoặc chân chữ X'),
                                            ('ankle pain', 'Đau mắt cá chân'),
                                            ('bones are painful', 'Xương đau'),
                                            ('knee weakness', 'Yếu khớp gối'),
                                            ('elbow pain', 'Đau khuỷu tay'),
                                            ('knee swelling', 'Sưng đầu gối'),
                                            ('skin moles', 'Nốt ruồi trên da'),
                                            ('knee lump or mass', 'Khối u hoặc cục u đầu gối'),
                                            ('weight gain', 'Tăng cân'),
                                            ('problems with movement', 'Vấn đề với chuyển động'),
                                            ('knee stiffness or tightness', 'Cứng hoặc thắt chặt đầu gối'),
                                            ('leg swelling', 'Sưng chân'),
                                            ('foot or toe swelling', 'Sưng chân hoặc ngón chân'),
                                            ('heartburn', 'Ợ nóng'),
                                            ('smoking problems', 'Vấn đề với thuốc lá'),
                                            ('muscle pain', 'Đau cơ'),
                                            ('infant feeding problem', 'Vấn đề cho trẻ bú'),
                                            ('recent weight loss', 'Giảm cân gần đây'),
                                            ('problems with shape or size of breast', 'Vấn đề với hình dạng hoặc kích thước vú'),
                                            ('underweight', 'Thiếu cân'),
                                            ('difficulty eating', 'Khó ăn'),
                                            ('scanty menstrual flow', 'Kinh nguyệt ít'),
                                            ('vaginal pain', 'Đau âm đạo'),
                                            ('vaginal redness', 'Đỏ âm đạo'),
                                            ('vulvar irritation', 'Kích ứng âm hộ'),
                                            ('weakness', 'Yếu đuối'),
                                            ('decreased heart rate', 'Nhịp tim chậm'),
                                            ('increased heart rate', 'Nhịp tim nhanh'),
                                            ('bleeding or discharge from nipple', 'Chảy máu hoặc tiết dịch từ núm vú'),
                                            ('ringing in ear', 'Ù tai'),
                                            ('plugged feeling in ear', 'Cảm giác tắc nghẽn tai'),
                                            ('itchy ear(s)', 'Ngứa tai'),
                                            ('frontal headache', 'Đau đầu vùng trán'),
                                            ('fluid in ear', 'Dịch trong tai'),
                                            ('neck stiffness or tightness', 'Cứng hoặc thắt chặt cổ'),
                                            ('spots or clouds in vision', 'Đốm hoặc mây trong tầm nhìn'),
                                            ('eye redness', 'Mắt đỏ'),
                                            ('lacrimation', 'Chảy nước mắt'),
                                            ('itchiness of eye', 'Ngứa mắt'),
                                            ('blindness', 'Mù lòa'),
                                            ('eye burns or stings', 'Mắt bị rát hoặc châm chích'),
                                            ('itchy eyelid', 'Ngứa mí mắt'),
                                            ('feeling cold', 'Cảm thấy lạnh'),
                                            ('decreased appetite', 'Chán ăn'),
                                            ('excessive appetite', 'Thèm ăn quá mức'),
                                            ('excessive anger', 'Giận dữ quá mức'),
                                            ('loss of sensation', 'Mất cảm giác'),
                                            ('focal weakness', 'Yếu cục bộ'),
                                            ('slurring words', 'Nói lắp'),
                                            ('symptoms of the face', 'Triệu chứng của khuôn mặt'),
                                            ('disturbance of memory', 'Rối loạn trí nhớ'),
                                            ('paresthesia', 'Cảm giác tê bì'),
                                            ('side pain', 'Đau bên'),
                                            ('fever', 'Sốt'),
                                            ('shoulder pain', 'Đau vai'),
                                            ('shoulder stiffness or tightness', 'Cứng hoặc thắt chặt vai'),
                                            ('shoulder weakness', 'Yếu vai'),
                                            ('arm cramps or spasms', 'Cơn co cứng tay'),
                                            ('shoulder swelling', 'Sưng vai'),
                                            ('tongue lesions', 'Tổn thương lưỡi'),
                                            ('leg cramps or spasms', 'Cơn co cứng chân'),
                                            ('abnormal appearing tongue', 'Lưỡi xuất hiện bất thường'),
                                            ('ache all over', 'Đau toàn thân'),
                                            ('lower body pain', 'Đau vùng dưới cơ thể'),
                                            ('problems during pregnancy', 'Vấn đề trong thai kỳ'),
                                            ('spotting or bleeding during pregnancy', 'Chảy máu hoặc rỉ máu trong thai kỳ'),
                                            ('cramps and spasms', 'Chuột rút và co cứng'),
                                            ('upper abdominal pain', 'Đau bụng trên'),
                                            ('stomach bloating', 'Chướng bụng'),
                                            ('changes in stool appearance', 'Thay đổi hình dạng phân'),
                                            ('unusual color or odor to urine', 'Màu sắc hoặc mùi hôi bất thường của nước tiểu'),
                                            ('kidney mass', 'Khối u thận'),
                                            ('swollen abdomen', 'Sưng bụng'),
                                            ('symptoms of prostate', 'Triệu chứng tuyến tiền liệt'),
                                            ('leg stiffness or tightness', 'Cứng hoặc thắt chặt chân'),
                                            ('difficulty breathing', 'Khó thở'),
                                            ('rib pain', 'Đau xương sườn'),
                                            ('joint pain', 'Đau khớp'),
                                            ('muscle stiffness or tightness', 'Cứng hoặc thắt chặt cơ'),
                                            ('pallor', 'Nhợt nhạt'),
                                            ('hand or finger lump or mass', 'Cục u hoặc khối u tay hoặc ngón tay'),
                                            ('chills', 'Rùng mình'),
                                            ('groin pain', 'Đau bẹn'),
                                            ('fatigue', 'Mệt mỏi'),
                                            ('abdominal distention', 'Phình bụng'),
                                            ('regurgitation.1', 'Trào ngược'),
                                            ('symptoms of the kidneys', 'Triệu chứng thận'),
                                            ('melena', 'Máu trong phân đen'),
                                            ('flushing', 'Đỏ bừng mặt'),
                                            ('coughing up sputum', 'Ho ra đờm'),
                                            ('seizures', 'Co giật'),
                                            ('delusions or hallucinations', 'Hoang tưởng hoặc ảo giác'),
                                            ('shoulder cramps or spasms', 'Cơn co cứng vai'),
                                            ('joint stiffness or tightness', 'Cứng hoặc thắt chặt khớp'),
                                            ('pain or soreness of breast', 'Đau hoặc nhức vú'),
                                            ('excessive urination at night', 'Đi tiểu quá mức vào ban đêm'),
                                            ('bleeding from eye', 'Chảy máu từ mắt'),
                                            ('rectal bleeding', 'Chảy máu trực tràng'),
                                            ('constipation', 'Táo bón'),
                                            ('temper problems', 'Vấn đề tính khí'),
                                            ('coryza', 'Cảm lạnh'),
                                            ('wrist weakness', 'Yếu cổ tay'),
                                            ('eye strain', 'Mỏi mắt'),
                                            ('hemoptysis', 'Khạc ra máu'),
                                            ('lymphedema', 'Phù bạch huyết');
-- Thêm các triệu chứng vào bảng Symptoms
INSERT INTO Symptoms (name_en, name_vi) VALUES
                                            ('skin on leg or foot looks infected', 'Da chân hoặc bàn chân trông bị nhiễm trùng'),
                                            ('allergic reaction', 'Phản ứng dị ứng'),
                                            ('congestion in chest', 'Tắc nghẽn trong ngực'),
                                            ('muscle swelling', 'Sưng cơ'),
                                            ('pus in urine', 'Mủ trong nước tiểu'),
                                            ('abnormal size or shape of ear', 'Kích thước hoặc hình dạng tai bất thường'),
                                            ('low back weakness', 'Yếu vùng lưng dưới'),
                                            ('sleepiness', 'Buồn ngủ'),
                                            ('apnea', 'Ngừng thở'),
                                            ('abnormal breathing sounds', 'Âm thanh thở bất thường'),
                                            ('excessive growth', 'Tăng trưởng quá mức'),
                                            ('elbow cramps or spasms', 'Cơn co thắt hoặc co cứng khuỷu tay'),
                                            ('feeling hot and cold', 'Cảm giác nóng và lạnh'),
                                            ('blood clots during menstrual periods', 'Cục máu đông trong kỳ kinh'),
                                            ('absence of menstruation', 'Mất kinh nguyệt'),
                                            ('pulling at ears', 'Kéo tai'),
                                            ('gum pain', 'Đau nướu'),
                                            ('redness in ear', 'Đỏ tai'),
                                            ('fluid retention', 'Giữ nước trong cơ thể'),
                                            ('flu-like syndrome', 'Hội chứng giống cúm'),
                                            ('sinus congestion', 'Tắc nghẽn xoang'),
                                            ('painful sinuses', 'Đau xoang'),
                                            ('fears and phobias', 'Lo sợ và ám ảnh'),
                                            ('recent pregnancy', 'Mang thai gần đây'),
                                            ('uterine contractions', 'Co thắt tử cung'),
                                            ('burning chest pain', 'Đau ngực nóng rát'),
                                            ('back cramps or spasms', 'Cơn co thắt hoặc co cứng lưng'),
                                            ('stiffness all over', 'Cứng người toàn thân'),
                                            ('muscle cramps, contractures, or spasms', 'Chuột rút, co rút cơ hoặc co cứng'),
                                            ('low back cramps or spasms', 'Cơn co thắt hoặc co cứng lưng dưới'),
                                            ('back mass or lump', 'Khối u hoặc cục u lưng'),
                                            ('nosebleed', 'Chảy máu mũi'),
                                            ('long menstrual periods', 'Kỳ kinh kéo dài'),
                                            ('heavy menstrual flow', 'Kinh nguyệt ra nhiều'),
                                            ('unpredictable menstruation', 'Kinh nguyệt không đều'),
                                            ('painful menstruation', 'Đau kinh nguyệt'),
                                            ('infertility', 'Hiếm muộn'),
                                            ('frequent menstruation', 'Kinh nguyệt thường xuyên'),
                                            ('sweating', 'Ra mồ hôi'),
                                            ('mass on eyelid', 'Khối u trên mí mắt'),
                                            ('swollen eye', 'Mắt sưng'),
                                            ('eyelid swelling', 'Sưng mí mắt'),
                                            ('eyelid lesion or rash', 'Tổn thương hoặc phát ban mí mắt'),
                                            ('unwanted hair', 'Lông không mong muốn'),
                                            ('symptoms of bladder', 'Triệu chứng của bàng quang'),
                                            ('irregular appearing nails', 'Móng tay bất thường'),
                                            ('itching of skin', 'Ngứa da'),
                                            ('hurts to breath', 'Đau khi thở'),
                                            ('nailbiting', 'Cắn móng tay'),
                                            ('skin dryness, peeling, scaliness, or roughness', 'Da khô, bong tróc, sần sùi hoặc thô ráp'),
                                            ('skin on arm or hand looks infected', 'Da trên tay hoặc bàn tay trông bị nhiễm trùng'),
                                            ('skin irritation', 'Kích ứng da'),
                                            ('itchy scalp', 'Ngứa da đầu'),
                                            ('hip swelling', 'Sưng hông'),
                                            ('incontinence of stool', 'Không kiểm soát được phân'),
                                            ('foot or toe cramps or spasms', 'Cơn co thắt hoặc co cứng chân hoặc ngón chân'),
                                            ('warts', 'Mụn cóc'),
                                            ('bumps on penis', 'Cục u trên dương vật'),
                                            ('too little hair', 'Ít tóc'),
                                            ('foot or toe lump or mass', 'Cục u hoặc khối u chân hoặc ngón chân'),
                                            ('skin rash', 'Phát ban da'),
                                            ('mass or swelling around the anus', 'Khối u hoặc sưng quanh hậu môn'),
                                            ('low back swelling', 'Sưng lưng dưới'),
                                            ('ankle swelling', 'Sưng mắt cá chân'),
                                            ('hip lump or mass', 'Khối u hoặc cục u hông'),
                                            ('drainage in throat', 'Chảy dịch trong cổ họng'),
                                            ('dry or flaky scalp', 'Da đầu khô hoặc bong tróc'),
                                            ('premenstrual tension or irritability', 'Căng thẳng hoặc cáu kỉnh trước kỳ kinh'),
                                            ('feeling hot', 'Cảm giác nóng'),
                                            ('feet turned in', 'Chân xoay vào trong'),
                                            ('foot or toe stiffness or tightness', 'Cứng hoặc thắt chặt chân hoặc ngón chân'),
                                            ('pelvic pressure', 'Áp lực vùng chậu'),
                                            ('elbow swelling', 'Sưng khuỷu tay'),
                                            ('elbow stiffness or tightness', 'Cứng hoặc thắt chặt khuỷu tay'),
                                            ('early or late onset of menopause', 'Bắt đầu mãn kinh sớm hoặc muộn'),
                                            ('mass on ear', 'Khối u trên tai'),
                                            ('bleeding from ear', 'Chảy máu từ tai'),
                                            ('hand or finger weakness', 'Yếu tay hoặc ngón tay'),
                                            ('low self-esteem', 'Tự ti'),
                                            ('throat irritation', 'Kích ứng cổ họng'),
                                            ('itching of the anus', 'Ngứa hậu môn'),
                                            ('swollen or red tonsils', 'Amidan sưng hoặc đỏ'),
                                            ('irregular belly button', 'Rốn bất thường'),
                                            ('swollen tongue', 'Lưỡi sưng'),
                                            ('lip sore', 'Lở môi'),
                                            ('vulvar sore', 'Lở âm hộ'),
                                            ('hip stiffness or tightness', 'Cứng hoặc thắt chặt hông'),
                                            ('mouth pain', 'Đau miệng'),
                                            ('arm weakness', 'Yếu tay'),
                                            ('leg lump or mass', 'Khối u hoặc cục u chân'),
                                            ('disturbance of smell or taste', 'Rối loạn khứu giác hoặc vị giác'),
                                            ('discharge in stools', 'Dịch trong phân'),
                                            ('penis pain', 'Đau dương vật'),
                                            ('loss of sex drive', 'Mất ham muốn tình dục'),
                                            ('obsessions and compulsions', 'Ám ảnh và hành vi cưỡng chế'),
                                            ('antisocial behavior', 'Hành vi chống đối xã hội'),
                                            ('neck cramps or spasms', 'Cơn co thắt hoặc co cứng cổ'),
                                            ('pupils unequal', 'Con ngươi không đều'),
                                            ('poor circulation', 'Duy trì tuần hoàn kém'),
                                            ('thirst', 'Khát'),
                                            ('sleepwalking', 'Mộng du'),
                                            ('skin oiliness', 'Da nhờn'),
                                            ('sneezing', 'Hắt hơi'),
                                            ('bladder mass', 'Khối u bàng quang'),
                                            ('knee cramps or spasms', 'Cơn co thắt hoặc co cứng đầu gối'),
                                            ('premature ejaculation', 'Xuất tinh sớm'),
                                            ('leg weakness', 'Yếu chân'),
                                            ('posture problems', 'Vấn đề với tư thế'),
                                            ('bleeding in mouth', 'Chảy máu trong miệng'),
                                            ('tongue bleeding', 'Chảy máu lưỡi'),
                                            ('change in skin mole size or color', 'Thay đổi kích thước hoặc màu sắc nốt ruồi'),
                                            ('penis redness', 'Đỏ dương vật'),
                                            ('penile discharge', 'Tiết dịch dương vật'),
                                            ('shoulder lump or mass', 'Khối u hoặc cục u vai'),
                                            ('polyuria', 'Tiểu nhiều'),
                                            ('cloudy eye', 'Mắt đục'),
                                            ('hysterical behavior', 'Hành vi hưng phấn'),
                                            ('arm lump or mass', 'Khối u hoặc cục u tay'),
                                            ('nightmares', 'Ác mộng'),
                                            ('bleeding gums', 'Chảy máu lợi'),
                                            ('pain in gums', 'Đau lợi'),
                                            ('bedwetting', 'Đái dầm'),
                                            ('diaper rash', 'Hăm tã'),
                                            ('lump or mass of breast', 'Khối u hoặc cục u vú'),
                                            ('vaginal bleeding after menopause', 'Chảy máu âm đạo sau mãn kinh'),
                                            ('infrequent menstruation', 'Kinh nguyệt không đều'),
                                            ('mass on vulva', 'Khối u âm hộ'),
                                            ('jaw pain', 'Đau hàm'),
                                            ('itching of scrotum', 'Ngứa bìu'),
                                            ('postpartum problems of the breast', 'Vấn đề sau sinh của vú'),
                                            ('eyelid retracted', 'Mí mắt co lại'),
                                            ('hesitancy', 'Chần chừ'),
                                            ('elbow lump or mass', 'Khối u hoặc cục u khuỷu tay'),
                                            ('muscle weakness', 'Yếu cơ'),
                                            ('throat redness', 'Đỏ cổ họng'),
                                            ('joint swelling', 'Sưng khớp'),
                                            ('tongue pain', 'Đau lưỡi'),
                                            ('redness in or around nose', 'Đỏ trong hoặc xung quanh mũi'),
                                            ('wrinkles on skin', 'Nếp nhăn trên da'),
                                            ('foot or toe weakness', 'Yếu chân hoặc ngón chân'),
                                            ('hand or finger cramps or spasms', 'Cơn co thắt hoặc co cứng tay hoặc ngón tay'),
                                            ('back stiffness or tightness', 'Cứng hoặc thắt chặt lưng'),
                                            ('wrist lump or mass', 'Khối u hoặc cục u cổ tay'),
                                            ('skin pain', 'Đau da'),
                                            ('low back stiffness or tightness', 'Cứng hoặc thắt chặt lưng dưới'),
                                            ('low urine output', 'Ít nước tiểu'),
                                            ('skin on head or neck looks infected', 'Da đầu hoặc cổ trông bị nhiễm trùng'),
                                            ('stuttering or stammering', 'Nói lắp'),
                                            ('problems with orgasm', 'Vấn đề với cực khoái'),
                                            ('nose deformity', 'Dị tật mũi'),
                                            ('lump over jaw', 'Khối u trên hàm'),
                                            ('sore in nose', 'Lở trong mũi'),
                                            ('hip weakness', 'Yếu hông'),
                                            ('back swelling', 'Sưng lưng'),
                                            ('ankle stiffness or tightness', 'Cứng hoặc thắt chặt mắt cá chân'),
                                            ('ankle weakness', 'Yếu mắt cá chân'),
                                            ('neck weakness', 'Yếu cổ');
